// Date: 8/10/2015 4:33:07 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.nath99000.toughertools.Entity.Render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class CaveMite extends ModelBase
{
  //fields
    ModelRenderer Head;
    ModelRenderer Eye1;
    ModelRenderer Eye2;
    ModelRenderer BodyA;
    ModelRenderer Tail;
    ModelRenderer BodyC;
    ModelRenderer BodyB;
    ModelRenderer BodySides;
    ModelRenderer BodyTop;
    ModelRenderer Mouth;
    ModelRenderer SpikeA;
    ModelRenderer SpikeB;
    ModelRenderer SpikeC;
    ModelRenderer Fang2;
    ModelRenderer Fang1;
    ModelRenderer Fang3;
    ModelRenderer Fang4;
  
  public CaveMite()
  {
    textureWidth = 32;
    textureHeight = 32;
    
      Head = new ModelRenderer(this, 0, 0);
      Head.addBox(0F, 0F, 0F, 4, 3, 2);
      Head.setRotationPoint(-2F, 21F, -6F);
      Head.setTextureSize(64, 32);
      Head.mirror = true;
      setRotation(Head, 0F, 0F, 0F);
      Eye1 = new ModelRenderer(this, 23, 16);
      Eye1.addBox(0F, 0F, 0F, 2, 2, 2);
      Eye1.setRotationPoint(1F, 20F, -7F);
      Eye1.setTextureSize(64, 32);
      Eye1.mirror = true;
      setRotation(Eye1, 0F, 0F, 0F);
      Eye2 = new ModelRenderer(this, 23, 16);
      Eye2.addBox(0F, 0F, 0F, 2, 2, 2);
      Eye2.setRotationPoint(-3F, 20F, -7F);
      Eye2.setTextureSize(64, 32);
      Eye2.mirror = true;
      setRotation(Eye2, 0F, 0F, 0F);
      BodyA = new ModelRenderer(this, 0, 0);
      BodyA.addBox(0F, 0F, 0F, 7, 4, 7);
      BodyA.setRotationPoint(-3.5F, 20F, -4F);
      BodyA.setTextureSize(64, 32);
      BodyA.mirror = true;
      setRotation(BodyA, 0F, 0F, 0F);
      Tail = new ModelRenderer(this, 0, 0);
      Tail.addBox(0F, 0F, 0F, 3, 1, 5);
      Tail.setRotationPoint(-1.5F, 23F, 3F);
      Tail.setTextureSize(64, 32);
      Tail.mirror = true;
      setRotation(Tail, 0F, 0F, 0F);
      BodyC = new ModelRenderer(this, 0, 0);
      BodyC.addBox(0F, 0F, 0F, 6, 3, 2);
      BodyC.setRotationPoint(-3F, 21F, 3F);
      BodyC.setTextureSize(64, 32);
      BodyC.mirror = true;
      setRotation(BodyC, 0F, 0F, 0F);
      BodyB = new ModelRenderer(this, 0, 0);
      BodyB.addBox(0F, 0F, 0F, 4, 2, 2);
      BodyB.setRotationPoint(-2F, 22F, 5F);
      BodyB.setTextureSize(64, 32);
      BodyB.mirror = true;
      setRotation(BodyB, 0F, 0F, 0F);
      BodySides = new ModelRenderer(this, 0, 0);
      BodySides.addBox(0F, 0F, 0F, 8, 3, 5);
      BodySides.setRotationPoint(-4F, 21F, -3F);
      BodySides.setTextureSize(64, 32);
      BodySides.mirror = true;
      setRotation(BodySides, 0F, 0F, 0F);
      BodyTop = new ModelRenderer(this, 0, 0);
      BodyTop.addBox(0F, 0F, 0F, 4, 1, 5);
      BodyTop.setRotationPoint(-2F, 19.5F, -3F);
      BodyTop.setTextureSize(64, 32);
      BodyTop.mirror = true;
      setRotation(BodyTop, 0F, 0F, 0F);
      Mouth = new ModelRenderer(this, 16, 17);
      Mouth.addBox(0F, 0F, 0F, 2, 1, 1);
      Mouth.setRotationPoint(-1F, 23F, -6.1F);
      Mouth.setTextureSize(64, 32);
      Mouth.mirror = true;
      setRotation(Mouth, 0F, 0F, 0F);
      SpikeA = new ModelRenderer(this, 0, 0);
      SpikeA.addBox(0F, 0F, 0F, 1, 2, 1);
      SpikeA.setRotationPoint(-0.5F, 18F, -1F);
      SpikeA.setTextureSize(64, 32);
      SpikeA.mirror = true;
      setRotation(SpikeA, 0F, 0F, 0F);
      SpikeB = new ModelRenderer(this, 0, 0);
      SpikeB.addBox(0F, 0F, 0F, 1, 2, 1);
      SpikeB.setRotationPoint(-0.5F, 18.5F, 2F);
      SpikeB.setTextureSize(64, 32);
      SpikeB.mirror = true;
      setRotation(SpikeB, -0.260246F, 0F, 0F);
      SpikeC = new ModelRenderer(this, 0, 0);
      SpikeC.addBox(0F, 0F, 0F, 1, 2, 1);
      SpikeC.setRotationPoint(-0.5F, 20F, 5F);
      SpikeC.setTextureSize(64, 32);
      SpikeC.mirror = true;
      setRotation(SpikeC, -0.5204921F, 0F, 0F);
      Fang2 = new ModelRenderer(this, 2, 20);
      Fang2.addBox(0F, 0F, 0F, 1, 1, 1);
      Fang2.setRotationPoint(0F, 23F, -5.7F);
      Fang2.setTextureSize(32, 32);
      Fang2.mirror = true;
      setRotation(Fang2, 0F, 0.4833219F, 0F);
      Fang1 = new ModelRenderer(this, 2, 17);
      Fang1.addBox(0F, 0F, 0F, 1, 1, 1);
      Fang1.setRotationPoint(-1F, 23F, -5.7F);
      Fang1.setTextureSize(32, 32);
      Fang1.mirror = true;
      setRotation(Fang1, 0F, 0.4833219F, 0F);
      Fang3 = new ModelRenderer(this, 6, 17);
      Fang3.addBox(0F, 0F, 0F, 1, 1, 1);
      Fang3.setRotationPoint(-1.5F, 23F, -5.7F);
      Fang3.setTextureSize(32, 32);
      Fang3.mirror = true;
      setRotation(Fang3, 0F, 0.4833219F, 0F);
      Fang4 = new ModelRenderer(this, 7, 20);
      Fang4.addBox(0F, 0F, 0F, 1, 1, 1);
      Fang4.setRotationPoint(-0.5F, 23F, -5.7F);
      Fang4.setTextureSize(32, 32);
      Fang4.mirror = true;
      setRotation(Fang4, 0F, 0.4833219F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Head.render(f5);
    Eye1.render(f5);
    Eye2.render(f5);
    BodyA.render(f5);
    Tail.render(f5);
    BodyC.render(f5);
    BodyB.render(f5);
    BodySides.render(f5);
    BodyTop.render(f5);
    Mouth.render(f5);
    SpikeA.render(f5);
    SpikeB.render(f5);
    SpikeC.render(f5);
    Fang2.render(f5);
    Fang1.render(f5);
    Fang3.render(f5);
    Fang4.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
