// Date: 8/8/2015 8:15:12 AM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.toughertools.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class SnowLauncher extends ModelBase
{
  //fields
    ModelRenderer Handle1;
    ModelRenderer Barrel;
    ModelRenderer Handle2;
  
  public SnowLauncher()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Handle1 = new ModelRenderer(this, 0, 0);
      Handle1.addBox(0F, 0F, 0F, 1, 2, 1);
      Handle1.setRotationPoint(0F, 22F, 0F);
      Handle1.setTextureSize(64, 32);
      Handle1.mirror = true;
      setRotation(Handle1, 0F, 0F, 0F);
      Barrel = new ModelRenderer(this, 0, 0);
      Barrel.addBox(0F, 0F, 0F, 4, 4, 9);
      Barrel.setRotationPoint(-2F, 18F, 0F);
      Barrel.setTextureSize(64, 32);
      Barrel.mirror = true;
      setRotation(Barrel, 0F, 0F, 0F);
      Handle2 = new ModelRenderer(this, 0, 0);
      Handle2.addBox(0F, 0F, 0F, 1, 3, 1);
      Handle2.setRotationPoint(0F, 13F, 0F);
      Handle2.setTextureSize(64, 32);
      Handle2.mirror = true;
      setRotation(Handle2, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5);
    Handle1.render(f5);
    Barrel.render(f5);
    Handle2.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, null);
  }

}
